export enum ActionType {
    ShuffleDeck,
    Attack,
    AttackFailed,
    CardReceived,
    BombDefused,
    BombExploded,
    DrawCard,
    SkipTurn,
    FutureSeen,
    NopeUsed,
    FavorAttack,
    TwoWildCardAttack,
    ThreeWildCardAttack,
}