name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    environment: testing
    strategy:
      matrix:
        node-version: [23.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Make backend .env
      run: |
          cat > .env << EOF
          PORT=8000
          PGHOST=localhost
          PGPORT=5432
          PGUSER=admin
          PGPASSWORD=${{ secrets.PGPASSWORD }}
          PGDATABASE=katboom
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF
      
    - name: Make backend .env.test
      run: |
          cat > .env.test << EOF
          PORT=8000
          PGHOST=localhost
          PGPORT=5432
          PGUSER=admin
          PGPASSWORD=${{ secrets.PGPASSWORD }}
          PGDATABASE=katboom_testing
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF
      

    - name: 'Install packages'
      run: npm ci

    - name: 'Build app'
      run: npm run build --if-present

    - name: 'Start database'
      run: 'npm run compose:up -- -d --wait database'

    - name: 'Run tests'
      run: npm run test
